#!/usr/bin/env python3.11
"""Build GHL Custom-HTML payloads from the CE static site pages.

Each payload = the page's <body> inner HTML, with:
  - site.css inlined as a <style> block (prepended)
  - site.js inlined as a <script> block (appended)
  - relative asset URLs (img/, css/, js/) absolutized to the live domain
  - internal .html links rewritten extensionless (/pools.html -> /pools)
  - STAGING mode: analytics stripped (gtag/fbq/noscript pixels) so builder
    visits never pollute CE's GA4/pixel mid-measurement-window. Regenerate
    with STAGING=False at cutover to restore tracking verbatim.

Also emits seo_manifest.json: per-page title / meta description / canonical
pulled from the static head, for the GHL SEO panel.
"""
import json
import re
from pathlib import Path

STAGING = True  # flip False at cutover regen: restores analytics
LIVE = "https://creativeedgeoutdoorliving.ca"
SITE = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent / "payloads"

# The replica page set: static filename -> GHL path (extensionless)
PAGES = {
    "index.html": "home",  # GHL homepage path handled at publish; body identical
    "pools.html": "pools",
    "outdoor-living.html": "outdoor-living",
    "retaining-walls.html": "retaining-walls",
    "about.html": "about",
    "services.html": "services",
    "design.html": "design",
    "our-work.html": "our-work",
    "commercial.html": "commercial",
    "contact.html": "contact",
    "blog.html": "blog",
    "blog-immerspa-pools-spas.html": "blog/immerspa-pools-spas",
    "blog-landscape-design-vernon.html": "blog/landscape-design-vernon",
    "blog-spring-garden-refresh.html": "blog/spring-garden-refresh",
    "privacy-policy.html": "privacy-policy",
    "terms.html": "terms",
    "thank-you.html": "thank-you",
    "lp-pools.html": "lp-pools",
    "lp-outdoor-living.html": "lp-outdoor-living",
    "lp-retaining-walls.html": "lp-retaining-walls",
}


def extract(head_html, pattern):
    m = re.search(pattern, head_html, re.S | re.I)
    return m.group(1).strip() if m else ""


def build_page(fname, ghl_path):
    raw = (SITE / fname).read_text()
    head = raw.split("</head>")[0]
    body = re.search(r"<body[^>]*>(.*)</body>", raw, re.S).group(1)

    if STAGING:
        # strip noscript tracking pixels (facebook.com/tr, googletagmanager)
        body = re.sub(r"<noscript>\s*<img[^>]*(facebook\.com/tr|googletagmanager)[^>]*>\s*</noscript>", "<!-- staging: tracking pixel stripped -->", body)

    # absolutize relative asset refs in body (img/, css/, js/, plain filenames)
    body = re.sub(r'(src|href)="(img|css|js)/', rf'\1="{LIVE}/\2/', body)
    # srcset holds comma-separated "url width" pairs — absolutize each relative entry
    body = re.sub(r'srcset="([^"]*)"', lambda m: 'srcset="' + re.sub(r'(^|,\s*)(img/)', rf'\1{LIVE}/\2', m.group(1)) + '"', body)

    # internal links: /?foo.html -> extensionless replica path
    def relink(m):
        attr, target = m.group(1), m.group(2)
        target_clean = target.lstrip("/")
        if target_clean in PAGES:
            p = PAGES[target_clean]
            return f'{attr}="/{"" if p == "home" else p}"'
        return m.group(0)
    body = re.sub(r'(href)="/?([a-z0-9-]+\.html)(?:")', lambda m: relink(m), body)

    css = (SITE / "css" / "site.css").read_text()
    js = (SITE / "js" / "site.js").read_text()
    if STAGING:
        # neuter analytics calls in site.js without changing structure:
        # gtag/fbq stubs mean form-logic still runs but nothing sends.
        js = "window.gtag=window.gtag||function(){};window.fbq=window.fbq||function(){};/* staging stubs */\n" + js

    payload = (
        f"<!-- CE GHL replica payload: {fname} -> /{ghl_path} | staging={STAGING} | generated by build_replica.py -->\n"
        f"<style>\n{css}\n</style>\n"
        f"{body}\n"
        f"<script>\n{js}\n</script>\n"
    )

    seo = {
        "title": extract(head, r"<title>(.*?)</title>"),
        "description": extract(head, r'<meta name="description" content="(.*?)"'),
        "canonical": extract(head, r'<link rel="canonical" href="(.*?)"'),
        "schema": re.findall(r'<script type="application/ld\+json">(.*?)</script>', head, re.S),
    }
    return payload, seo


def main():
    OUT.mkdir(exist_ok=True)
    manifest = {}
    for fname, ghl_path in PAGES.items():
        if not (SITE / fname).exists():
            print(f"SKIP (missing): {fname}")
            continue
        payload, seo = build_page(fname, ghl_path)
        out = OUT / (ghl_path.replace("/", "__") + ".html")
        out.write_text(payload)
        manifest[ghl_path] = {"source": fname, "payload": out.name, "bytes": len(payload), **seo}
        print(f"{fname:38s} -> {out.name:44s} {len(payload):7,d} b")
    (OUT / "seo_manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"\n{len(manifest)} payloads, staging={STAGING}")


if __name__ == "__main__":
    main()
